### ISSUE TITLE
CentOS6 molecule failure

### ISSUE THREAD

**Issue by cinek810** [mplachter/docker-centos6-molecule#1]
I tried to run CentOS6 molecule.  Failed and then googling I found your project. Does this output seem anyhow similar to you?
Simply trying '''docker exec''' on anything in the container fails with:
<code>
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247 [...]
</code>
Raw output from molecule (failing task) is:
<code>
    fatal: [MoleculeCentOS6]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:110: decoding init error from pipe caused \\\"read parent: connection reset by peer\\\"\"/.ansible/tmp/ansible-tmp-1549406437.3-44243398360021 `\" && echo ansible-tmp-1549406437.3-44243398360021=\"` echo rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:110: decoding init error from pipe caused \\\"read parent: connection reset by peer\\\"\"/.ansible/tmp/ansible-tmp-1549406437.3-44243398360021 `\" ), exited with result 126, stdout output: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:110: decoding init error from pipe caused \\\"read parent: connection reset by peer\\\"\"\n\r\n", "unreachable": true}</code>

**Comment by mplachter** [comment]
Are you trying to change the default path of Ansible in the Ansible or Moluecle config?

**Comment by cinek810** [comment]
The issue was caused by mistake in packaging in last docker rpm in CentOS7.  [yum downgrad fixed it](https://access.redhat.com/solutions/3734981). Thanks for your time!
